# Copyright (c) ByteDance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

add_executable(bolt_codec_benchmark CodecBenchmark.cpp)

target_link_libraries(
  bolt_codec_benchmark
  PRIVATE
    bolt_testutils
    Folly::folly
    ${FOLLY_BENCHMARK}
    glog::glog
)

add_executable(bolt_block_payload_benchmark BlockPayloadBenchmark.cpp)

target_link_libraries(
  bolt_block_payload_benchmark
  PRIVATE
    bolt_testutils
    Folly::folly
    ${FOLLY_BENCHMARK}
    glog::glog
)

add_executable(bolt_cell_split_benchmark CellSplitBenchmark.cpp)

target_link_libraries(
    bolt_cell_split_benchmark
    PRIVATE
        bolt_shuffle_spark_impl
        bolt_testutils
        Folly::folly
        ${FOLLY_BENCHMARK}
        glog::glog
)
