/*
 * Demo: Pre-compile C/C++ to LLVM bitcode at build time,
 *       embed into binary, load at runtime into ThrustJIT.
 *
 * Three common embedding approaches are shown below.
 * The test at the bottom demonstrates the full round-trip.
 */

#ifdef ENABLE_BOLT_JIT

#include <gtest/gtest.h>
#include <llvm/Bitcode/BitcodeReader.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Verifier.h>
#include <llvm/Support/MemoryBuffer.h>

#include "bolt/jit/ThrustJIT.h"

// ================================================================
// ██  Approach 1: CMake custom_command + xxd (most portable)
// ================================================================
//
// Idea: clang compiles .cpp → .bc, then xxd converts .bc → .h
//       with a C byte array. The .h is #include'd at compile time.
//
// --- CMakeLists.txt snippet ---
//
//   # Step 1: Compile helper functions to LLVM bitcode
//   add_custom_command(
//     OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//     COMMAND clang++ -emit-llvm -c -O2
//             -std=c++17
//             ${CMAKE_CURRENT_SOURCE_DIR}/runtime_helpers.cpp
//             -o ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//     DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/runtime_helpers.cpp
//     COMMENT "Compiling runtime_helpers.cpp to LLVM bitcode"
//   )
//
//   # Step 2: Convert bitcode to C header with byte array
//   add_custom_command(
//     OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers_bc.h
//     COMMAND xxd -i runtime_helpers.bc > runtime_helpers_bc.h
//     WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
//     DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//     COMMENT "Embedding runtime_helpers.bc as C byte array"
//   )
//
//   # Step 3: Add generated header to include path
//   target_include_directories(my_target PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
//
// --- Generated runtime_helpers_bc.h looks like: ---
//
//   unsigned char runtime_helpers_bc[] = {
//     0xde, 0xc0, 0x17, 0x0b,  // bitcode magic number
//     0x00, 0x00, 0x00, 0x00,
//     ...
//   };
//   unsigned int runtime_helpers_bc_len = 1234;
//
// --- Usage: ---
//
//   #include "runtime_helpers_bc.h"
//   auto buf = llvm::MemoryBuffer::getMemBuffer(
//       llvm::StringRef((const char*)runtime_helpers_bc,
//                       runtime_helpers_bc_len),
//       "runtime_helpers.bc", /*RequiresNullTerminator=*/false);

// ================================================================
// ██  Approach 2: ld / objcopy embed as ELF symbol (Linux only)
// ================================================================
//
// --- CMakeLists.txt snippet ---
//
//   # Compile to bitcode
//   add_custom_command(
//     OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//     COMMAND clang++ -emit-llvm -c -O2
//             ${CMAKE_CURRENT_SOURCE_DIR}/runtime_helpers.cpp
//             -o ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//     DEPENDS runtime_helpers.cpp
//   )
//
//   # Wrap bitcode as an ELF object with linker symbols
//   add_custom_command(
//     OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers_bc.o
//     COMMAND ld -r -b binary
//             -o runtime_helpers_bc.o
//             runtime_helpers.bc
//     WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
//     DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers.bc
//   )
//
//   # Link the .o into your target
//   target_sources(my_target PRIVATE
//     ${CMAKE_CURRENT_BINARY_DIR}/runtime_helpers_bc.o)
//
// --- Usage (extern symbols auto-generated by ld): ---
//
//   extern "C" {
//     extern const char _binary_runtime_helpers_bc_start[];
//     extern const char _binary_runtime_helpers_bc_end[];
//   }
//   size_t size = _binary_runtime_helpers_bc_end
//               - _binary_runtime_helpers_bc_start;
//   auto buf = llvm::MemoryBuffer::getMemBuffer(
//       llvm::StringRef(_binary_runtime_helpers_bc_start, size),
//       "runtime_helpers.bc", false);

// ================================================================
// ██  Approach 3: CMake string(CONFIGURE) + constexpr (C++17)
// ================================================================
//
// For small IR snippets, embed LLVM IR text directly via
// CMake configure_file. No clang -emit-llvm needed.
//
// --- runtime_helpers.ir.in ---
//
//   constexpr const char kRuntimeHelpersIR[] = R"IR(
//   target datalayout = "@LLVM_DATA_LAYOUT@"
//   target triple = "@LLVM_TARGET_TRIPLE@"
//
//   define i64 @fast_add(i64 %a, i64 %b) {
//     %r = add i64 %a, %b
//     ret i64 %r
//   }
//   )IR";
//
// --- CMakeLists.txt ---
//
//   configure_file(runtime_helpers.ir.in runtime_helpers_ir.h @ONLY)

// ================================================================
// ██  Complete runnable test using approach 1 simulation
// ================================================================
//
// Since we can't run clang during this test's build, we simulate
// approach 1 by generating bitcode from IRBuilder at test time,
// then showing the load-from-buffer path (parseBitcodeFile).

namespace bytedance::bolt::jit::test {

using namespace bolt::jit;

class EmbedBitcodeTest : public ::testing::Test {
 protected:
  ThrustJIT* jit = ThrustJIT::getInstance();
};

/// Helper: generate a bitcode buffer containing `int64_t add(int64_t, int64_t)`
/// In production this would be a pre-built .bc file embedded as a byte array.
static std::unique_ptr<llvm::MemoryBuffer> createSampleBitcode() {
  // Create a standalone module with its own context
  auto ctx = std::make_unique<llvm::LLVMContext>();
  auto mod = std::make_unique<llvm::Module>("precompiled_helpers", *ctx);

  // Build: int64_t precompiled_add(int64_t a, int64_t b) { return a + b; }
  auto* i64Ty = llvm::Type::getInt64Ty(*ctx);
  auto* funcTy = llvm::FunctionType::get(i64Ty, {i64Ty, i64Ty}, false);
  auto* func = llvm::Function::Create(
      funcTy, llvm::Function::ExternalLinkage, "precompiled_add", *mod);

  auto args = func->arg_begin();
  llvm::Value* a = args++;
  a->setName("a");
  llvm::Value* b = args++;
  b->setName("b");

  auto* bb = llvm::BasicBlock::Create(*ctx, "entry", func);
  llvm::IRBuilder<> builder(bb);
  builder.CreateRet(builder.CreateAdd(a, b, "sum"));

  // Serialize module to bitcode in memory (simulates .bc file content)
  std::string bitcodeStr;
  llvm::raw_string_ostream os(bitcodeStr);
  llvm::WriteBitcodeToFile(*mod, os);
  os.flush();

  // Return as MemoryBuffer (same as reading from embedded byte array)
  return llvm::MemoryBuffer::getMemBufferCopy(
      llvm::StringRef(bitcodeStr.data(), bitcodeStr.size()),
      "precompiled_helpers.bc");
}

/// Demonstrate: load pre-compiled bitcode into ThrustJIT and execute
TEST_F(EmbedBitcodeTest, LoadPrecompiledBitcode) {
  // ---- In production, this buffer comes from embedded byte array: ----
  //   #include "runtime_helpers_bc.h"   // generated by xxd
  //   auto buf = MemoryBuffer::getMemBuffer(
  //       StringRef((const char*)runtime_helpers_bc, runtime_helpers_bc_len),
  //       "runtime_helpers.bc", false);
  //
  // Here we simulate it:
  auto buf = createSampleBitcode();
  ASSERT_NE(buf, nullptr);

  std::string funcName = "precompiled_add";

  // Step 1: Create a thread-safe module
  auto tsm = jit->CreateTSModule(funcName);

  // Step 2: Parse the bitcode buffer and link into the module
  tsm.withModuleDo([&](llvm::Module& targetModule) {
    // Parse bitcode from the embedded buffer
    auto expectedModule = llvm::parseBitcodeFile(
        buf->getMemBufferRef(), targetModule.getContext());

    ASSERT_TRUE(!!expectedModule) << "Failed to parse bitcode";
    auto& srcModule = *expectedModule.get();

    // Link all functions from pre-compiled module into target module.
    // This is the key step — we copy function definitions from the
    // pre-compiled bitcode into the JIT module, where LLVM can inline
    // them into dynamically generated code.
    for (auto& func : srcModule) {
      if (func.isDeclaration())
        continue;

      // Clone function into target module
      auto* newFunc = llvm::Function::Create(
          func.getFunctionType(),
          llvm::Function::ExternalLinkage,
          func.getName(),
          targetModule);

      // Map values for cloning
      llvm::ValueToValueMapTy vmap;
      auto newArgIt = newFunc->arg_begin();
      for (auto& oldArg : func.args()) {
        vmap[&oldArg] = &*newArgIt++;
      }

      // Clone function body
      llvm::SmallVector<llvm::ReturnInst*, 4> returns;
      llvm::CloneFunctionInto(
          newFunc, &func, vmap,
          llvm::CloneFunctionChangeType::DifferentModule, returns);
    }
  });

  // Step 3: Compile to native code (LLVM optimization passes will run)
  CompiledModuleSP mod = jit->CompileModule(std::move(tsm));
  ASSERT_NE(mod, nullptr);

  // Step 4: Execute
  using AddFunc = int64_t (*)(int64_t, int64_t);
  auto func = (AddFunc)mod->getFuncPtr(funcName);
  ASSERT_NE(func, nullptr);

  EXPECT_EQ(func(1, 2), 3);
  EXPECT_EQ(func(100, 200), 300);
  EXPECT_EQ(func(-10, 10), 0);
}

/// Simpler alternative: use Linker::linkModules to merge entire modules
TEST_F(EmbedBitcodeTest, LoadPrecompiledBitcodeWithLinker) {
  auto buf = createSampleBitcode();
  ASSERT_NE(buf, nullptr);

  std::string funcName = "precompiled_add";
  auto tsm = jit->CreateTSModule(funcName);

  tsm.withModuleDo([&](llvm::Module& targetModule) {
    auto expectedModule = llvm::parseBitcodeFile(
        buf->getMemBufferRef(), targetModule.getContext());
    ASSERT_TRUE(!!expectedModule);

    // One-liner: link entire pre-compiled module into target
    bool err = llvm::Linker::linkModules(
        targetModule, std::move(expectedModule.get()));
    ASSERT_FALSE(err) << "Linker::linkModules failed";
  });

  CompiledModuleSP mod = jit->CompileModule(std::move(tsm));
  ASSERT_NE(mod, nullptr);

  using AddFunc = int64_t (*)(int64_t, int64_t);
  auto func = (AddFunc)mod->getFuncPtr(funcName);
  ASSERT_NE(func, nullptr);

  EXPECT_EQ(func(42, 58), 100);
}

} // namespace bytedance::bolt::jit::test

#endif // ENABLE_BOLT_JIT
